version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - revive
    - misspell
    - gocritic
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: unused-parameter
          disabled: true
    gocritic:
      disabled-checks:
        - exitAfterDefer
